### ISSUE TITLE
Paper-card tries to load image even when not specified

### ISSUE THREAD

**Issue by masterl** [PolymerElements/paper-card#17]
Well, I'm experiencing this problem on Ruby on Rails.
Here's what I've done (if I didn't forget something)
- Added the gem "polimer-rails".
- Ran `rails g polymer:install` (after bundling, of course)
- Installed paper-card via `bower` (it's put inside `vendor/assets/components`)
- Added `Rails.application.config.assets.paths << Rails.root.join('vendor', 'assets', 'components', '**')` to `config/initializers/assets.rb`.

*.bowerrc*:
```
{
  "directory": "vendor/assets/components"
}
```

*bower.json*:
```
"dependencies": {
    "paper-card": "PolymerElements/paper-card#~1.0.3"
  }
```

Inside `app/assets/components/application.html.erb`:
```
//= require paper-card/paper-card
```
The above file is included on application's layout file.

*app/assets/javascripts/application.js*:
```
//= require webcomponentsjs/webcomponents.min
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```

In my view I use:
```
paper-card heading="paper card test"
  .card-content Card test
```
It's written using slim.

As you can see, I did't specify an image. I just inserted some text.

The card gets rendered:
![image](https://cloud.githubusercontent.com/assets/5068286/9598286/6c2d8bca-5060-11e5-8117-995c205069ac.png)

But, I get this when watching the server:
```
Started GET "/assets/%5B%5Bimage%5D%5D" for 127.0.0.1 at 2015-09-01 04:16:59 -0300

ActionController::RoutingError (No route matches [GET] "/assets/%5B%5Bimage%5D%5D"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.13.4) lib/puma/server.rb:541:in `handle_request'
  puma (2.13.4) lib/puma/server.rb:388:in `process_client'
  puma (2.13.4) lib/puma/server.rb:270:in `block in run'
  puma (2.13.4) lib/puma/thread_pool.rb:106:in `call'
  puma (2.13.4) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (0.9ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (24.7ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (17.7ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (34.3ms)
```

**Comment by masterl** [comment]
I don't know if I did something wrong on the back-end.

I tried removing the paper-card component and reloading the page and the image get request doesn't occur.

The get request occurs only when the element is on the page.
Looking the element definition, I saw this:
```
<img hidden$="[[!image]]" src="[[image]]">
```

Looks like [[image]] isn't being replaced by the empty string.

Did I do something wrong?

**Comment by notwaldorf** [comment]
@masterl If I run the demo locally, I don't see any requests to the image, so I can't really repro this. Also, I don't know what `slim` is either (and I'm always suspicious of new things), so let's try to back up some steps :)

I would start by writing vanilla html, and see if the requests still happen. Perhaps a super simple `index.html` file that just imports polymer, `paper-card`, and uses a super simple card like this `<paper-card heading="Hi!"></paper-card>`.

**Comment by masterl** [comment]
Slim is like coffee is to JavaScript.
Indentation defines what's inside what, so I don't have to write closing tags, not even < >, so this:
```
paper-card heading="paper card test"
  .card-content Card test
```
Is translated to:
```
<paper-card heading="paper card test">
  <div class="card-content">
     Card test
  </div>
</paper-card>
```

I'll try doing what you suggested tomorrow.
I'll post the results when I do.
Thanks for the help.

**Comment by masterl** [comment]
Sorry for the delay. But the error keeps happening.

I changed the html for the one you suggested.

Here's the server log:
```
Started GET "/fallacies" for 127.0.0.1 at 2015-09-05 07:44:48 -0300
Processing by FallaciesController#index as HTML
  Fallacy Load (0.2ms)  SELECT "fallacies".* FROM "fallacies"
  Rendered fallacies/index.html.slim within layouts/application (9.0ms)
Completed 200 OK in 56ms (Views: 54.7ms | ActiveRecord: 0.2ms)


Started GET "/assets/fallacies.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/application.self-e80e8f2318043e8af94dddc2adad5a4f09739a8ebb323b3ab31cd71d45fd9113.css?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/scaffolds.self-312e26a640b125a0b01502797e2e1eb59a288ea87e3ac648c6213974435b2134.css?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/webcomponentsjs/webcomponents.min.self-d8127aa851cf1cac5b04ad3c77442a14296f0676ed8f538c632cc2c784a6075c.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/jquery_ujs.self-d456baa54c1fa6be2ec3711f0a72ddf7a5b2f34a6b4f515f33767d6207b7d4b3.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/turbolinks.self-c37727e9bd6b2735da5c311aa83fead54ed0be6cc8bd9a65309e9c5abe2cbfff.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/fallacies.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/application.self-81b3bdfbbb36dac4c4063731e02ec50a23c4f2845f59cb92017d0c0d35795b22.js?body=1" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/application-e1fc993c167ec82fd2f982fb4f0a8c210b2942151d1c4c9d0e544e011c539106.html" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

Started GET "/assets/%5B%5Bimage%5D%5D" for 127.0.0.1 at 2015-09-05 07:44:49 -0300

ActionController::RoutingError (No route matches [GET] "/assets/%5B%5Bimage%5D%5D"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.13.4) lib/puma/server.rb:541:in `handle_request'
  puma (2.13.4) lib/puma/server.rb:388:in `process_client'
  puma (2.13.4) lib/puma/server.rb:270:in `block in run'
  puma (2.13.4) lib/puma/thread_pool.rb:106:in `call'
  puma (2.13.4) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.5ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (0.9ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (34.1ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (16.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
  Rendered /home/leonardo/.rvm/gems/ruby-2.2.1/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (35.0ms)

Started GET "/assets/favicon-437f8c793eacdfd90aaf32b3f2c636a6631ce974d237f2a913189422a1262e2b.ico" for 127.0.0.1 at 2015-09-05 07:44:49 -0300
```

This is the HTML by showing source on the browser (Google Chrome):
```
<paper-card heading="Hi!" aria-label="Hi!" class="x-scope paper-card-0">
    <paper-material class="style-scope paper-card x-scope paper-material-0" elevation="1">
      <div class="header style-scope paper-card">
        <img src="http://localhost:3000/assets/%5B%5Bimage%5D%5D" class="style-scope paper-card" hidden="">
        <div class="title-text style-scope paper-card">Hi!</div>
      </div>
  </paper-material>
  </paper-card>
```

Is there any chance that the webcomponentsjs might be being mangled and not working correctly?

**Comment by masterl** [comment]
If it is of any help these are the versions of ruby and rails I'm using:
```
~/projects/logicfalacies  master ✗                                                                                                                                                                                           4d ⚑  
▶ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

~/projects/logicfalacies  master ✗                                                                                                                                                                                           4d ⚑  
▶ rails -v
Rails 4.2.4
```

And the Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.4)
      actionview (= 4.2.4)
      activesupport (= 4.2.4)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.4)
      activesupport (= 4.2.4)
      globalid (>= 0.3.0)
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (6.0.2)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    execjs (2.6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    i18n (0.7.0)
    jbuilder (2.3.1)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.8.0)
    multi_json (1.11.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nokogumbo (1.4.2)
      nokogiri
    polymer-rails (1.1.0)
      nokogiri (~> 1.6)
      nokogumbo (~> 1.1)
      rails (>= 3.1.0)
    puma (2.13.4)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.4)
      actionmailer (= 4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      activemodel (= 4.2.4)
      activerecord (= 4.2.4)
      activesupport (= 4.2.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.4)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.4)
      actionpack (= 4.2.4)
      activesupport (= 4.2.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    sass (3.4.18)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slim-rails (3.0.1)
      actionmailer (>= 3.1, < 5.0)
      actionpack (>= 3.1, < 5.0)
      activesupport (>= 3.1, < 5.0)
      railties (>= 3.1, < 5.0)
      slim (~> 3.0)
    spring (1.3.6)
    sprockets (3.3.4)
      rack (~> 1.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    temple (0.7.6)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.1.0)
  jbuilder (~> 2.0)
  jquery-rails
  polymer-rails
  puma
  rails (= 4.2.4)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  slim-rails
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.10.6
```

**Comment by masterl** [comment]
Do the variable substitution doesn't work if it's prefixed with "/assets/" ?

From what I understand, the component is parsed and [[image]] is prefixed with /assets/

**Comment by notwaldorf** [comment]
`[[image]]` is just a variable, and will be replaced with whatever you pass it, using data binding. If you don't pass it anything, then the `src` attribute will be empty.

However, what seems to be happening is that slim is escaping the `[[` and `]]` inside the `<paper-card>` image element (because it's loading `/assets/%5B%5Bimage%5D%5D`, which is actually `[[image]]`)

I don't know if this is slim or the rails asset pipeline, because I don't speak slim nor rails, but somehow you have to tell one of these things to stop escaping HTML like that. In any case, this isn't something that we can fix :cry:. Sorry!

**Comment by masterl** [comment]
It's rails that does it.
But the fact that /assets/[[image]] isn't translated to /assets/ still bugs me, because the [[image]] placeholder should have been replaced by empty string...

Thanks, anyway. :)

**Comment by notwaldorf** [comment]
I think the parser escapes the `[[` in `[[image]]` before Polymer gets to it, which is why there's no substitution going on.

**Comment by masterl** [comment]
Omg! Of course!
How didn't I see that? XD

Thanks and sorry for this issue, I should have noticed this before.

**Comment by notwaldorf** [comment]
No worries!

**Comment by WuPei** [comment]
@masterl I understand that the parser escapes the `[[`, before it reaches polymer, how did you configure the asset pipeline to make it not substituting `[[` with `%5B%5B` ?

**Comment by masterl** [comment]
If I'm not mistaken, I didn't.
This was just a trial I've done and since I didn't want to expend time to fix this, I just quit.

If I'm not mistaken, I used Polymer with nodejs easily.
